#!/bin/bash

./make-datapoint.py --file patch.list 2>err.log